# Generated by Django 3.0.7 on 2020-06-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('course_title', models.CharField(max_length=256)),
                ('contact_hour', models.IntegerField()),
                ('credit_hour', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prerequisite', models.CharField(blank=True, max_length=10, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'courses',
            },
        ),
    ]
