# Generated by Django 3.0.7 on 2020-06-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='contact_hour',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='credit_hour',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisite',
        ),
    ]
